//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_НедвижимостьДетали
    {
        public int Недвижимость_ID { get; set; }
        public string Адрес { get; set; }
        public Nullable<decimal> Площадь { get; set; }
        public Nullable<int> Количество_комнат { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Описание { get; set; }
        public Nullable<int> Этаж { get; set; }
        public Nullable<int> Этажность_здания { get; set; }
        public Nullable<int> Год_постройки { get; set; }
        public Nullable<bool> Наличие_балкона_лоджии { get; set; }
        public Nullable<bool> Наличие_парковки { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Дата_изменения_статуса { get; set; }
        public byte[] Фотография { get; set; }
        public string Владелец { get; set; }
        public string Контактный_номер_телефона { get; set; }
        public Nullable<int> Количество_фото { get; set; }
        public string Тип_недвижимости { get; set; }
        public string Отопление { get; set; }
        public string Водоснабжение { get; set; }
        public string Канализация { get; set; }
    }
}
