//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int Документ_ID { get; set; }
        public Nullable<int> Владелец_ID { get; set; }
        public string ТипДокумента { get; set; }
        public string Название { get; set; }
        public Nullable<System.DateTime> ДатаВыдачи { get; set; }
        public Nullable<System.DateTime> ДействителенДо { get; set; }
        public Nullable<int> Недвижимость_ID { get; set; }
        public string СсылкаНаДокумент { get; set; }
        public string Статус { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Недвижимость Недвижимость { get; set; }
    }
}
