//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДополнительныеУслуги
    {
        public int Услуга_ID { get; set; }
        public Nullable<int> Сделка_ID { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Договоры Договоры { get; set; }
    }
}
