//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договоры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Договоры()
        {
            this.ДополнительныеУслуги = new HashSet<ДополнительныеУслуги>();
            this.ОперацииСНедвижимостью = new HashSet<ОперацииСНедвижимостью>();
        }
    
        public int Сделка_ID { get; set; }
        public string Вид_основной_оказ_услуг { get; set; }
        public Nullable<System.DateTime> Дата_сделки { get; set; }
        public Nullable<decimal> Сумма_сделки { get; set; }
        public Nullable<int> Недвижимость_ID { get; set; }
        public Nullable<int> Клиент_ID { get; set; }
        public Nullable<int> Сотрудник_ID { get; set; }
        public string Комментарии { get; set; }
    
        public virtual Недвижимость Недвижимость { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДополнительныеУслуги> ДополнительныеУслуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОперацииСНедвижимостью> ОперацииСНедвижимостью { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
    }
}
