//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Недвижимость
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Недвижимость()
        {
            this.Договоры = new HashSet<Договоры>();
            this.Документы = new HashSet<Документы>();
            this.ОценкиНедвижимости = new HashSet<ОценкиНедвижимости>();
            this.СтатусНедвижимости = new HashSet<СтатусНедвижимости>();
            this.ФотографииНедвижимости = new HashSet<ФотографииНедвижимости>();
        }
    
        public int Недвижимость_ID { get; set; }
        public string Адрес { get; set; }
        public Nullable<decimal> Площадь { get; set; }
        public Nullable<int> Количество_комнат { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Описание { get; set; }
        public string Тип_недвижимости { get; set; }
        public Nullable<int> Этаж { get; set; }
        public Nullable<int> Этажность_здания { get; set; }
        public Nullable<int> Год_постройки { get; set; }
        public Nullable<bool> Наличие_балкона_лоджии { get; set; }
        public Nullable<bool> Наличие_парковки { get; set; }
        public string Отопление { get; set; }
        public string Водоснабжение { get; set; }
        public string Канализация { get; set; }
        public Nullable<int> Владелец_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договоры> Договоры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Документы> Документы { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОценкиНедвижимости> ОценкиНедвижимости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтатусНедвижимости> СтатусНедвижимости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФотографииНедвижимости> ФотографииНедвижимости { get; set; }
    }
}
