//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОперацииСНедвижимостью
    {
        public int Операция_ID { get; set; }
        public Nullable<int> Сделка_ID { get; set; }
        public string Наименование_услуги { get; set; }
        public Nullable<System.DateTime> Дата_операции { get; set; }
        public Nullable<decimal> Сумма_операции { get; set; }
        public string Комментарии { get; set; }
    
        public virtual Договоры Договоры { get; set; }
    }
}
