//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class СтатусНедвижимости
    {
        public int Статус_ID { get; set; }
        public Nullable<int> Недвижимость_ID { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Дата_изменения_статуса { get; set; }
    
        public virtual Недвижимость Недвижимость { get; set; }
    }
}
